In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("/Users/charles.martineau/Dropbox/Teaching/Rotman/RSM3034H/data/clean/event_earnings_data_20260704_233953.parquet")

In [7]:
panel = pd.read_parquet("/Users/charles.martineau/Dropbox/Teaching/Rotman/RSM3034H/data/clean/panel_data_20260704_212056.parquet")

In [15]:
panel.head()

,date,permno,shrout,cfacpr,cfacshr,openprc,ticker,comnam,exchcd,shrcd,...,abn_ret,neg_ret,neg_abn_ret,abs_abn_ret,mcap,ln_mcap,mcap_qnt,bm_qnt,ln_ret,ff_port
0,1986-01-08,10000,3680.0,1.0,1.0,<NA>,OMFGA,OPTIMUM MANUFACTURING INC,3,10,...,-0.00299,1,1,0.00299,9200000.0,16.034714,0.0,NaN,-0.024692,NaN
1,1986-01-09,10000,3680.0,1.0,1.0,<NA>,OMFGA,OPTIMUM MANUFACTURING INC,3,10,...,0.0114,0,0,0.0114,9200000.0,16.034714,0.0,NaN,0.0,NaN
2,1986-01-10,10000,3680.0,1.0,1.0,<NA>,OMFGA,OPTIMUM MANUFACTURING INC,3,10,...,-0.0001,0,1,0.0001,9200000.0,16.034714,0.0,NaN,0.0,NaN
3,1986-01-13,10000,3680.0,1.0,1.0,<NA>,OMFGA,OPTIMUM MANUFACTURING INC,3,10,...,0.0469,0,0,0.0469,9660000.0,16.083504,0.0,NaN,0.04879,NaN
4,1986-01-14,10000,3680.0,1.0,1.0,<NA>,OMFGA,OPTIMUM MANUFACTURING INC,3,10,...,0.047319,0,0,0.047319,10120000.0,16.130024,0.0,NaN,0.04652,NaN

In [16]:
len(panel[(panel['ea'] == 1) & (panel['prc']>1) &
          (panel['date']<='2023-12-31') & (panel['date']>='1984-01-01') &
          (panel['sue'].notna()) & (panel['bm_ratio'].notna()) & (panel['mcap']>5000000) ])

354235

In [4]:
# remove obs with no sue
df = df[df["sue"].notna()]

In [27]:
test = df[(df['event_t']==0) & (df['date']<='2023-12-31') & (df['date']>='1984-01-01')]

In [42]:
test[test['permno'] == 14593]

,date,permno,gvkey,prc,openprc,ret,mkt,mkt_rf,smb,hml,...,ff_port,sue,sue_qnt,mcap,mcap_qnt,event_t,ea_date,ann_ret,ann_ret_qnt,year
2938187,1986-01-07,14593,001690,23.0,<NA>,0.033708,0.0141,0.0138,-0.0049,0.0006,...,0.0117,0.008889,4.0,1.432647e+09,3.0,0,1986-01-07,0.033708,4,1986
2938260,1986-01-15,14593,001690,23.875,<NA>,0.026882,0.0082,0.0079,-0.0008,-0.0020,...,0.0065,0.018636,4.0,1.487150e+09,3.0,0,1986-01-15,0.026882,3,1986
2938333,1986-04-17,14593,001690,29.0,<NA>,0.026549,0.0035,0.0033,0.0035,-0.0019,...,-0.0008,-0.000354,1.0,1.838919e+09,4.0,0,1986-04-17,0.026549,3,1986
2938406,1986-07-17,14593,001690,32.25,<NA>,-0.037313,0.0048,0.0046,-0.0019,-0.0046,...,0.0021,0.000557,2.0,2.061517e+09,4.0,0,1986-07-17,-0.037313,0,1986
2938479,1986-10-15,14593,001690,33.375,<NA>,-0.018382,0.0123,0.0121,-0.0056,-0.0050,...,0.0156,0.001493,3.0,2.090210e+09,4.0,0,1986-10-15,-0.018382,1,1986
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2947677,2022-10-27,14593,001690,144.8,148.07001,-0.030465,-0.0053,-0.0054,0.0044,0.0108,...,-0.0099,-0.000072,1.0,2.303495e+12,4.0,0,2022-10-27,-0.030465,0,2022
2947750,2023-02-02,14593,001690,150.82001,148.89999,0.037063,0.0156,0.0154,0.0115,-0.0207,...,0.0279,-0.000154,1.0,2.386266e+12,4.0,0,2023-02-02,0.037063,4,2023
2947823,2023-05-04,14593,001690,165.78999,164.89,-0.009913,-0.0076,-0.0078,-0.0052,-0.0104,...,-0.0045,0.000546,2.0,2.607661e+12,4.0,0,2023-05-04,-0.009913,1,2023
2947896,2023-08-03,14593,001690,191.17,191.57001,-0.007322,-0.0017,-0.0019,0.0002,0.0008,...,-0.0018,0.000312,2.0,2.988796e+12,4.0,0,2023-08-03,-0.007322,1,2023
2947969,2023-11-02,14593,001690,177.57001,175.52,0.020693,0.0196,0.0194,0.0072,0.0163,...,0.0187,0.000350,2.0,2.761702e+12,4.0,0,2023-11-02,0.020693,3,2023

In [31]:
n=test[(test['event_t'] == 0) & (test['sue'].notna()) & (test['prc']>1) & (test['mcap']>5000000)].groupby(['permno', 'year'])['sue'].count().reset_index().rename(columns={'sue': 'count'}).sort_values(by='count', ascending=False)

In [32]:
n.sum()

permno    7031162808
year       231635194
count         357654
dtype: int64

In [47]:
ibes = pd.read_parquet("/Users/charles.martineau/Dropbox/Teaching/Rotman/RSM3034H/data/preprocess_cache/ibes_sue_20260704_070306.parquet")

In [48]:
ibes = ibes[(ibes['sue'].notna()) & (ibes['datetime']<='2023-12-31') & (ibes['datetime']>='1984-01-31')]

In [49]:
ibes[ibes['permno'] == 14593].sort_values(by='datetime', ascending=False).tail(20)

,gvkey,ticker,permno,conm,datetime,fpedats,rdq,rdq1,datadate,leadrdq1,repdats,medest,act,numest,sue_rw1,sue_rw2,sue,forecast_disp_std,forecast_disp_max_min
8848,001690,AAPL,14593.0,APPLE INC,1991-04-15,1991-03-31,1991-04-15,1991-04-15,1991-03-31,1991-07-17,1991-04-15,1.2,1.07,17,0.000441,0.000441,-0.001912,0.133458,0.491036
8849,001690,AAPL,14593.0,APPLE INC,1990-07-18,1990-06-30,1990-07-18,1990-07-18,1990-06-30,1990-10-18,1990-07-18,0.97,0.96,17,0.004916,0.004916,-0.000223,0.073495,0.303571
8850,001690,AAPL,14593.0,APPLE INC,1989-04-19,1989-03-31,1989-04-18,1989-04-18,1989-03-31,1989-07-18,1989-04-19,0.4,0.44,29,-0.004772,-0.004772,0.001123,0.054994,0.837012
8851,001690,AAPL,14593.0,APPLE INC,1989-01-17,1988-12-31,1989-01-17,1989-01-17,1988-12-31,1989-04-18,1989-01-17,1.05,1.1,24,0.004472,0.004472,0.001242,0.055161,0.206411
8852,001690,AAPL,14593.0,APPLE INC,1988-07-20,1988-06-30,1988-07-19,1988-07-19,1988-06-30,NaT,1988-07-20,0.655,0.71,20,0.006703,0.006703,0.001189,0.034043,0.243531
8853,001690,AAPL,14593.0,APPLE INC,1988-04-19,1988-03-31,1988-04-18,1988-04-18,1988-03-31,1988-07-19,1988-04-19,0.5,0.61,16,0.008875,0.008875,0.00275,0.085479,0.784314
8854,001690,AAPL,14593.0,APPLE INC,1988-01-21,1987-12-31,1988-01-20,1988-01-20,1987-12-31,1988-04-18,1988-01-21,0.72,0.92,17,0.011071,0.011071,0.004762,0.098619,0.378648
8855,001690,AAPL,14593.0,APPLE INC,1987-10-14,1987-09-30,1987-10-14,1987-10-14,1987-09-30,1988-01-20,1987-10-14,0.45,0.54,11,0.005044,0.005044,0.001593,0.03145,0.217822
8856,001690,AAPL,14593.0,APPLE INC,1987-07-14,1987-06-30,1987-07-14,1987-07-14,1987-06-30,1987-10-14,1987-07-14,0.325,0.4,6,0.003827,0.003827,0.001852,0.084715,0.810811
8857,001690,AAPL,14593.0,APPLE INC,1987-04-15,1987-03-31,1987-04-15,1987-04-15,1987-03-31,1987-07-14,1987-04-15,0.44,0.5,11,0.000155,0.000155,0.00093,0.032697,0.279661
8858,001690,AAPL,14593.0,APPLE INC,1987-01-20,1986-12-31,1987-01-20,1987-01-20,1986-12-31,1987-04-15,1987-01-20,0.92,0.92,9,0.0,0.0,0.0,0.031623,0.107143
8859,001690,AAPL,14593.0,APPLE INC,1986-10-15,1986-09-30,1986-10-15,1986-10-15,1986-09-30,1987-01-20,1986-10-15,0.45,0.5,8,0.004478,0.005535,0.001493,0.026186,0.130435
8860,001690,AAPL,14593.0,APPLE INC,1986-07-17,1986-06-30,1986-07-17,1986-07-17,1986-06-30,1986-10-15,1986-07-17,0.46,0.48,11,0.021463,0.009639,0.000557,0.058837,0.357724
8861,001690,AAPL,14593.0,APPLE INC,1986-04-17,1986-03-31,1986-04-17,1986-04-17,1986-03-31,1986-07-17,1986-04-17,0.5,0.49,10,0.012035,0.012035,-0.000354,0.082624,0.517241
8862,001690,AAPL,14593.0,APPLE INC,1986-01-15,1985-12-31,1986-01-15,1986-01-15,1985-12-31,1986-04-17,1986-01-15,0.5,0.91,9,0.007273,0.007273,0.018636,0.072801,0.452055
8863,001690,AAPL,14593.0,APPLE INC,1985-10-18,1985-09-30,1985-10-18,1985-10-18,1985-09-30,1986-01-15,1985-10-18,0.22,0.36,11,-0.008889,<NA>,0.008889,0.073904,1.037736
8864,001690,AAPL,14593.0,APPLE INC,1985-07-18,1985-06-30,1985-07-18,1985-07-18,1985-06-30,1985-10-18,1985-07-18,0.01,-0.28,10,-0.032222,<NA>,-0.016111,0.266175,24.615385
8865,001690,AAPL,14593.0,APPLE INC,1985-01-18,1984-12-31,1985-01-18,1985-01-18,1984-12-31,1985-04-17,1985-01-18,0.6,0.75,8,0.022318,<NA>,0.00515,0.155288,0.821429
8866,001690,AAPL,14593.0,APPLE INC,1984-10-19,1984-09-30,1984-10-18,1984-10-18,1984-09-30,1985-01-18,1984-10-19,0.44,0.5,2,0.016716,0.016716,0.002388,0.0,0.0
8867,001690,AAPL,14593.0,APPLE INC,1984-07-15,1984-06-30,1984-07-16,1984-07-16,1984-06-30,1984-10-18,1984-07-15,0.29,0.3,4,-0.003774,-0.003774,0.000377,0.034157,0.271186

In [45]:
ibes['datetime'].min()

Timestamp('1985-01-01 00:00:00')